[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm run install:all"
]

[phases.install.env]
NODE_ENV = "development"

[phases.build]
cmds = [
  "npm run build",
  "rm -rf public && cp -r frontend/dist public"
]

[start]
cmd = "npm start"
